# Generated by Django 5.1.1 on 2024-10-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_rename_version_sign_version_is_current"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="version",
            options={
                "ordering": ["-is_current", "version_number"],
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
            },
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.UniqueConstraint(
                fields=("product", "version_number"), name="unique_product_version"
            ),
        ),
    ]
