# Generated by Django 5.1.1 on 2024-11-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["product_name", "product_description", "price"],
                "permissions": [
                    ("can_unpublish_product", "Может отменить публикацию продукта"),
                    ("can_change_description", "Может изменить описание продукта"),
                    ("can_change_category", "Может изменить категорию продукта"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
